spring.application.name=note-genie-admin
server.servlet.context-path=/note-genie
server.port=8082
com.square.api.client.env=SANDBOX
com.square.api.sandbox.application.id=sandbox-sq0idb-2-QFvB6xKA4uAA1VzuQ7eA
com.square.api.sandbox.access.token=EAAAlyUwR_hk2ycjfoHIyRFdDMxl45TlpS_lyPZ8xjk0_HtZM8h2drQLPvfq0zlL
com.square.api.sandbox.oauth=sandbox-sq0csb-LCKJYBMT1O_1cnznpGvXQglECNe2ZxbyXBZiW2uBzdo
com.square.api.oauth.application.secret=sq0csp-jXHHNI4-vZi86z2q53ksIEItbIT75LHEan3WrcJzLAk