spring.application.name=note-genie-admin
server.servlet.context-path=/note-genie
server.port=8082
com.square.api.client.env=PRODUCTION
com.square.api.prod.application.id=sq0idp-3IqsDRM8VI0p1TI47EoJXw
com.square.api.prod.access.token=EAAAl4R9xj2EqeJGgasnwEZGw9WQ3538oamTmEBM-vG2gZA9UBWEbbcymWFsImoN\

com.square.api.sandbox.oauth=sandbox-sq0csb-LCKJYBMT1O_1cnznpGvXQglECNe2ZxbyXBZiW2uBzdo
com.square.api.oauth.application.secret=sq0csp-jXHHNI4-vZi86z2q53ksIEItbIT75LHEan3WrcJzLAk
spring.datasource.url=jdbc:postgresql://localhost:5432/note_genie_admin
spring.datasource.username=note_genie
spring.datasource.password=Imei9f2u!
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto = create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect