-- ADMIN DDL ====
BEGIN;

CREATE TABLE APP_USER (
  ID BIGSERIAL PRIMARY KEY,
  USERNAME VARCHAR NOT NULL,
  PASSWORD VARCHAR NOT NULL,
  EMAIL VARCHAR,
  PHONE_NUMBER VARCHAR,
  CREATED_TIMESTAMP TIMESTAMP WITHOUT TIME ZONE,
  EDITED_TIMESTAMP TIMESTAMP WITHOUT TIME ZONE,
  STATUS_CODE CHAR(3) CHECK STATUS_CODE IN ('ACT', 'INA', 'SUS')
);

CREATE INDEX app_user_username_idx ON app_user (username);

CREATE INDEX app_user_phone_nbr_idx ON app_user (phone_number);

CREATE INDEX status_cd_idx ON app_user (status_code);

CREATE INDEX created_timestamp ON app_user (created_timestamp);

--==========================================================
CREATE TABLE CUSTOMER (
  ID BIGSERIAL PRIMARY KEY,
  USER_ID BIGINT REFERENCES APP_USER (ID),
  FIRST_NAME VARCHAR NOT NULL,
  LAST_NAME VARCHAR NOT NULL,
  ADDRESS_LINE_A VARCHAR,
  ADDRESS_LINE_B VARCHAR,
  CITY VARCHAR,
  STATE VARCHAR,
  ZIP_CODE VARCHAR,
  IS_SUSPENDED CHAR(1) DEFAULT 'N'::BPCHAR,
  CREATED_TIMESTAMP TIMESTAMP WITHOUT TIME ZONE,
  EDITED_TIMESTAMP TIMESTAMP WITHOUT TIME ZONE,
  ZONE_ID VARCHAR NOT NULL DEFAULT 'America/Chicago',
  IS_SUSPENDED CHARACTER(1) DEFAULT 'N'::BPCHAR,
  STATUS_CODE CHAR(3) CHECK STATUS_CODE IN ('ACT', 'INA', 'SUS'),
);

CREATE INDEX CUSTOMER_IDX ON CUSTOMER (EMAIL);

CREATE INDEX is_suspended ON customer (is_suspended);

CREATE INDEX created_timestamp ON customer (created_timestamp);

--==========================================================
CREATE TABLE SUBSCRIPTION (
  ID BIGSERIAL PRIMARY KEY,
  CUSTOMER_ID BIGINT REFERENCES CUSTOMER (ID),
  PRODUCT_ID BIGINT REFERENCES PRODUCT (ID),
  PRICE NUMERIC(4, 2) NOT NULL DEFAULT '0.00',
  STATUS_CODE CHAR(3) CHECK STATUS_CODE IN ('ACT', 'INA', 'SUS'),
  NEXT_BILLING_DATE TIMESTAMP WITHOUT TIME ZONE,
  CREATED_TIMESTAMP TIMESTAMP WITHOUT TIME ZONE,
  EDITED_TIMESTAMP TIMESTAMP WITHOUT TIME ZONE
);

CREATE INDEX subscription_status_cd_idx ON subscription (status_code);

--==========================================================
CREATE TABLE INVOICE (
  ID BIGSERIAL PRIMARY KEY,
  CUSTOMER_ID BIGINT REFERENCES CUSTOMER (ID),
  TOTAL_AMOUNT NUMERIC(4, 2) NOT NULL DEFAULT '0.00',
  STATUS_CODE VARCHAR(3) NOT NULL CHECK STATUS_CODE IN (
    'CREATED',
    'SENT',
    'PAID',
    'CANCELLED',
    'DRAFT',
    'ERROR'
  ),
  PAYMENT_ID BIGINT,
  CREATED_TIMESTAMP TIMESTAMP WITHOUT TIME ZONE,
  EDITED_TIMESTAMP TIMESTAMP WITHOUT TIME ZONE
);

CREATE INDEX created_timestamp ON invoice (created_timestamp);

CREATE INDEX invoice_customer_idx ON invoice (customer_id);

CREATE status_cd_idx ON invoice (status_code);

--==========================================================
CREATE INVOICE_ITEM (
  ID BIGSERIAL PRIMARY KEY,
  INVOICE_ID BIGINT REFERENCES INVOICE (ID),
  QUANTITY INTEGER,
  PRICE NUMERIC(4, 2),
  TOTAL NUMERIC(4, 2),
  CREATE_TIMESTAMP TIMESTAMP WITHOUT TIME ZONE,
  EDITED_TIMESTAMP TIMESTAMP WITHOUT TIME ZONE
);

--==========================================================
CREATE PAYMENT (
  ID BIGSERIAL PRIMARY KEY,
  PAYMENT_ID BIGINT REFERENCES PAYMENT (ID),
  AMOUNT NUMERIC(4, 2),
  CURRENCY VARCHAR(3) NOT NULL DEFAULT 'USD',
  STATUS_CODE CHAR(3) NOT NULL CHECK STATUS_CODE IN (
    'PENDING',
    'COMPLETED',
    'FAILED',
    'CANCELLED',
    'REFUNDED',
    'ERROR'
  ),
  SQUARE_PAYMENT_ID TEXT NOT NULL,
  CREATED_TIMESTAMP TIMESTAMP WITHOUT TIME ZONE,
  EDITED_TIMESTAMP TIMESTAMP WITHOUT TIME ZONE
);

CREATE INDEX square_payment_id ON payment (square_payment_id);

CREATE INDEX payment_status_cd_idx ON payment (status_code);

CREATE INDEX payment_created_date_idx ON payment (created_timestamp);

--==========================================================
CREATE PAYMENT_TOKEN (
  ID BIGSERIAL PRIMARY KEY,
  SQUARE_CUSTOMER_ID NOT NULL,
  CUSTOMER_ID BIGINT REFERENCES CUSTOMER (ID),
  PAYMENT_TOKEN TEXT,
  STATUS_CODE CHAR(3) NOT NULL CHECK STATUS_CODE IN ('ACT', 'INA', 'SUS'),
  CREATED_TIMESTAMP TIMESTAMP WITHOUT TIME ZONE,
  EDITED_TIMESTAMP TIMESTAMP WITHOUT TIME ZONE
);

CREATE payment_tkn_square_customer_idx ON payment_token (square_customer_id);

--==========================================================
CREATE PRODUCT (
  ID BIGSERIAL PRIMARY KEY,
  NAME VARCHAR NOT NULL,
  PRICE NUMERIC(4, 2),
  STATUS_CODE CHAR(3) NOT NULL CHECK STATUS_CODE IN ('ACT', 'INA', 'SUS'),
  CREATED_TIMESTAMP TIMESTAMP WITHOUT TIME ZONE,
  EDITED_TIMESTAMP TIMESTAMP WITHOUT TIME ZONE
);

ROLLBACK;